### ISSUE TITLE
How to make it run on the GPU

### ISSUE THREAD

**Issue by tnn2018** [fmi-basel/neural-tangent-transfer#1]
It is a wonderful paper and I am interested in it.  
The problem I have is that I don't know how to make it run on the GPU.  
My current configuration is：
python 3.6.9
jax 0.2.9
jaxlib 0.1.61
Tensorflow can successfully find the GPU (tf.config.list_physical_devices('GPU')  test pass) .
Looking forward to your reply！

**Comment by fzenke** [comment]
Thanks for your feedback. Does your Jax version support GPU? Did you compile Jax from source?

**Comment by tnn2018** [comment]
Thank you very much for your reminding ！
I only installed the CPU-only version of jax and jaxlib.  The problem has been solved  after I installed the GPU version of Jax.
This link （https://github.com/google/jax#installation）has specific installation instructions for others  who need help.
